#' Line Cross data from Oakley et al.
#'
#' A subset of the data generated by Oakley et al.
#'
#' @format a data frame containing 800 rows and 3 columns:
#' \describe{
#'    \item{full_size}{whether or not a plant grew beyond a stunted rosette (deaths are included as 0's)}
#'    \item{anc_prop}{ancestry proportion, i.e. the proportion of the genome that comes from parent 2}
#'    \item{anc_het}{ancestry heterozygosity, i.e. the proportion of loci that are heterozygous for ancestry}
#' }
#' @source Oakley, C., Ågren, J. & Schemske, D. Heterosis and outbreeding depression in crosses between natural populations of Arabidopsis thaliana. Heredity 115, 73–82 (2015). https://doi.org/10.1038/hdy.2015.18
"oakley"
